# Custom Language File for Launcher Customizer

[ejs.app]
title = "LastSaviors Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/blueearthcat/LS-Launcher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/channel/UCQupU0o1_dQdCUN6TLr3Lug"
mediaDiscordURL = "https://discord.gg/9qUBNEzESd"

[ejs.settings]
sourceGithubLink = "https://github.com/blueearthcat/LS-Launcher"
supportLink = "https://github.com/blueearthcat/LS-Launcher/issues"

[ejs.welcome]
welcomeHeader = "라스트 세이비어스에 오신걸 환영합니다."
welcomeDescription = "RPG, 그 이상의 감동"
welcomeDescCTA = "마지막 세계를 구원할 자는, 당신입니다."
