name: Build and Release
on:
  push:
    tags:
      - 'v*'


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: npm ci
      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            npm run dist:win
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            npm run dist:mac
          else
            npm run dist:linux
          fi
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ls-launcher-${{ matrix.os }}
          path: dist/*
          retention-days: 1

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: Auto-generated release for LastSaviors Launcher ${{ github.ref_name }}
          draft: false
          prerelease: false
      - name: Upload Windows Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/ls-launcher-windows-latest/*setup*.exe
          asset_name: LastSaviors-Launcher-${{ github.ref_name }}-windows.exe
          asset_content_type: application/x-msdownload
      - name: Upload macOS Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/ls-launcher-macos-latest/*.dmg
          asset_name: LastSaviors-Launcher-${{ github.ref_name }}-macos.dmg
          asset_content_type: application/x-apple-diskimage
      - name: Upload Linux Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/ls-launcher-ubuntu-latest/*.AppImage
          asset_name: LastSaviors-Launcher-${{ github.ref_name }}-linux.AppImage
          asset_content_type: application/octet-stream
      - name: Upload Windows Update Metadata
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/ls-launcher-windows-latest/latest.yml
          asset_name: latest.yml
          asset_content_type: text/plain

      - name: Upload macOS Update Metadata
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/ls-launcher-macos-latest/latest-mac.yml
          asset_name: latest-mac.yml
          asset_content_type: text/plain