name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # 태그 푸시(v1.0.0 등)로 릴리스 트리거

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write  # 릴리스 생성 및 에셋 업로드 권한
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ls-launcher-${{ matrix.os }}
          path: dist/*
          retention-days: 1  # 아티팩트 보관 기간 (필요 시 조정)

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: Auto-generated release for LS-Launcher ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/LS-Launcher  # 실제 파일 이름으로 대체 필요
          asset_name: LS-Launcher-${{ github.ref_name }}-${{ matrix.os }}${{ matrix.os == 'macos-latest' && '.dmg' || matrix.os == 'ubuntu-latest' && '.AppImage' || '.exe' }}
          asset_content_type: ${{ matrix.os == 'macos-latest' && 'application/x-apple-diskimage' || matrix.os == 'ubuntu-latest' && 'application/octet-stream' || 'application/x-msdownload' }}