name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: npm ci
      - name: Build
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            npm run dist:win -- --publish never
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            npm run dist:mac -- --publish never
          else
            npm run dist:linux -- --publish never
          fi
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ls-launcher-${{ matrix.os }}
          path: |
            dist/*setup*.exe
            dist/*setup*.dmg
            dist/*.AppImage
          retention-days: 1

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      # Windows artifact 복사
      - name: Prepare Windows artifact
        shell: bash
        run: |
          mkdir -p artifacts/ls-launcher-windows-latest
          shopt -s nullglob
          for f in dist/*setup*.exe; do
            cp "$f" artifacts/ls-launcher-windows-latest/
          done

      # macOS artifact 복사
      - name: Prepare macOS artifact
        shell: bash
        run: |
          mkdir -p artifacts/ls-launcher-macos-latest
          shopt -s nullglob
          for f in dist/*.dmg; do
            cp "$f" artifacts/ls-launcher-macos-latest/
          done

      # Linux artifact 복사
      - name: Prepare Linux artifact
        shell: bash
        run: |
          mkdir -p artifacts/ls-launcher-ubuntu-latest
          shopt -s nullglob
          for f in dist/*.AppImage; do
            cp "$f" artifacts/ls-launcher-ubuntu-latest/
          done

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: Auto-generated release for LastSaviors Launcher ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Windows Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/ls-launcher-windows-latest/*setup*.exe
          asset_name: LastSaviors-Launcher-${{ github.ref_name }}-windows.exe
          asset_content_type: application/x-msdownload

      - name: Upload macOS Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/ls-launcher-macos-latest/*.dmg
          asset_name: LastSaviors-Launcher-${{ github.ref_name }}-macos.dmg
          asset_content_type: application/x-apple-diskimage

      - name: Upload Linux Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/ls-launcher-ubuntu-latest/*.AppImage
          asset_name: LastSaviors-Launcher-${{ github.ref_name }}-linux.AppImage
          asset_content_type: application/octet-stream
